from src.petl_enum import BaseEnum


class Delimiter(str, BaseEnum):
    DENOTE = ":",
    RETURN = "->",
    ASSIGN = "=",
    NEWLINE_SLASH = "\\",
    STMT_END = ";",
    RANGE = "..",
    PLUS = "+",
    MINUS = "-",
    MULTIPLY = "*",
    DIVIDE = "/",
    MODULUS = "%",
    GREATER_THAN = ">",
    LESS_THAN = "<",
    GREATER_THAN_EQ = ">=",
    LESS_THAN_EQ = "<=",
    EQUAL = "==",
    NOT_EQUAL = "!=",
    LIST_CONCAT = "++",
    PIPE = "|",
    PAREN_LEFT = "(",
    PAREN_RIGHT = ")",
    BRACKET_LEFT = "[",
    BRACKET_RIGHT = "]",
    BRACE_LEFT = "{",
    BRACE_RIGHT = "}",
    COMMNA = ",",
    CATCHALL = "_",
    CASE_EXP = "=>",
    BIRD = "|>",
    SCHEMA = "$"
