models:
  host: ollama
  port: 11434
  enabled: true
  core: qwen2.5:1.5b
  embed: nomic-embed-text

csv:
  directory: csvs
  max:
    files: 5
    size: 10000

cleanup:
  interval_seconds: 900

redis:
  host: redis
  port: 6379
  db: 0
  expire_seconds: 3600